name: netreg
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - bioconductor-qvalue=2.2.2
  - dask=2.0.0
  - dask-ml=1.0.0
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.24.2
  - python=3.6.8
  - pytest=5.0.0
  - r=3.6.0
  - r-argparse=2.0.1
  - r-devtools=2.0.2
  - r-ggplot2=3.1.1
  - r-rcolorbrewer=1.1_2
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - r-base=3.6.0

